# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import QDialog

from SettingController import AyarKontrolcu


class Ui_Settings(QDialog):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(660, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QtCore.QSize(660, 480))
        Settings.setMaximumSize(QtCore.QSize(660, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setSizeGripEnabled(False)
        self.groupBox_8 = QtWidgets.QGroupBox(Settings)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 401, 361))
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_5.setGeometry(QtCore.QRect(210, 130, 181, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setMinimumSize(QtCore.QSize(87, 0))
        self.label_7.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.leKatilimDurumuBaslangic = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.leKatilimDurumuBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leKatilimDurumuBaslangic.setText("")
        self.leKatilimDurumuBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leKatilimDurumuBaslangic.setObjectName("leKatilimDurumuBaslangic")
        self.horizontalLayout_7.addWidget(self.leKatilimDurumuBaslangic)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLineWidth(2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setIndent(0)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 181, 101))
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_13.setMinimumSize(QtCore.QSize(87, 0))
        self.label_13.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.leKKOpakBaslangic = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.leKKOpakBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leKKOpakBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leKKOpakBaslangic.setObjectName("leKKOpakBaslangic")
        self.horizontalLayout_11.addWidget(self.leKKOpakBaslangic)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_14.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.leKKOpakKarSayisi = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.leKKOpakKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leKKOpakKarSayisi.setAlignment(QtCore.Qt.AlignCenter)
        self.leKKOpakKarSayisi.setObjectName("leKKOpakKarSayisi")
        self.horizontalLayout_12.addWidget(self.leKKOpakKarSayisi)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 130, 181, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_9.setMinimumSize(QtCore.QSize(87, 0))
        self.label_9.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.leKitapTurBaslangic = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.leKitapTurBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leKitapTurBaslangic.setText("")
        self.leKitapTurBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leKitapTurBaslangic.setObjectName("leKitapTurBaslangic")
        self.horizontalLayout_9.addWidget(self.leKitapTurBaslangic)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setIndent(0)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 381, 101))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 341, 49))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbOpak = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbOpak.setObjectName("rbOpak")
        self.verticalLayout.addWidget(self.rbOpak)
        self.rbKKodu = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbKKodu.setObjectName("rbKKodu")
        self.verticalLayout.addWidget(self.rbKKodu)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setGeometry(QtCore.QRect(210, 240, 181, 101))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_15.setMinimumSize(QtCore.QSize(87, 0))
        self.label_15.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.leOgrenciNoBaslangic = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.leOgrenciNoBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leOgrenciNoBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leOgrenciNoBaslangic.setObjectName("leOgrenciNoBaslangic")
        self.horizontalLayout_13.addWidget(self.leOgrenciNoBaslangic)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_16.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.leOgrenciNoKarSayisi = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.leOgrenciNoKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leOgrenciNoKarSayisi.setAlignment(QtCore.Qt.AlignCenter)
        self.leOgrenciNoKarSayisi.setObjectName("leOgrenciNoKarSayisi")
        self.horizontalLayout_14.addWidget(self.leOgrenciNoKarSayisi)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.groupBox_9 = QtWidgets.QGroupBox(Settings)
        self.groupBox_9.setGeometry(QtCore.QRect(430, 10, 221, 361))
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 181, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(87, 0))
        self.label.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.leFenBaslangic = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leFenBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leFenBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leFenBaslangic.setObjectName("leFenBaslangic")
        self.horizontalLayout_2.addWidget(self.leFenBaslangic)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.leFenKarSayisi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leFenKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leFenKarSayisi.setAlignment(QtCore.Qt.AlignCenter)
        self.leFenKarSayisi.setObjectName("leFenKarSayisi")
        self.horizontalLayout.addWidget(self.leFenKarSayisi)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 181, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(87, 0))
        self.label_5.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.leTurBaslangic = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.leTurBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leTurBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leTurBaslangic.setObjectName("leTurBaslangic")
        self.horizontalLayout_5.addWidget(self.leTurBaslangic)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.leTurKarSayisi = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.leTurKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leTurKarSayisi.setAlignment(QtCore.Qt.AlignCenter)
        self.leTurKarSayisi.setObjectName("leTurKarSayisi")
        self.horizontalLayout_6.addWidget(self.leTurKarSayisi)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 130, 181, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setMinimumSize(QtCore.QSize(87, 0))
        self.label_3.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leMatBaslangic = QtWidgets.QLineEdit(self.layoutWidget2)
        self.leMatBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leMatBaslangic.setAlignment(QtCore.Qt.AlignCenter)
        self.leMatBaslangic.setObjectName("leMatBaslangic")
        self.horizontalLayout_3.addWidget(self.leMatBaslangic)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.leMatKarSayisi = QtWidgets.QLineEdit(self.layoutWidget2)
        self.leMatKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leMatKarSayisi.setAlignment(QtCore.Qt.AlignCenter)
        self.leMatKarSayisi.setObjectName("leMatKarSayisi")
        self.horizontalLayout_4.addWidget(self.leMatKarSayisi)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(Settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 390, 641, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setContentsMargins(180, 0, 180, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pbTamam = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTamam.sizePolicy().hasHeightForWidth())
        self.pbTamam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pbTamam.setFont(font)
        self.pbTamam.setStyleSheet("")
        self.pbTamam.setObjectName("pbTamam")
        self.verticalLayout_8.addWidget(self.pbTamam)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.rbOpak, self.rbKKodu)
        Settings.setTabOrder(self.rbKKodu, self.leKitapTurBaslangic)
        Settings.setTabOrder(self.leKitapTurBaslangic, self.leKatilimDurumuBaslangic)
        Settings.setTabOrder(self.leKatilimDurumuBaslangic, self.leKKOpakBaslangic)
        Settings.setTabOrder(self.leKKOpakBaslangic, self.leKKOpakKarSayisi)
        Settings.setTabOrder(self.leKKOpakKarSayisi, self.leOgrenciNoBaslangic)
        Settings.setTabOrder(self.leOgrenciNoBaslangic, self.leOgrenciNoKarSayisi)
        Settings.setTabOrder(self.leOgrenciNoKarSayisi, self.leTurBaslangic)
        Settings.setTabOrder(self.leTurBaslangic, self.leTurKarSayisi)
        Settings.setTabOrder(self.leTurKarSayisi, self.leMatBaslangic)
        Settings.setTabOrder(self.leMatBaslangic, self.leMatKarSayisi)
        Settings.setTabOrder(self.leMatKarSayisi, self.leFenBaslangic)
        Settings.setTabOrder(self.leFenBaslangic, self.leFenKarSayisi)
        Settings.setTabOrder(self.leFenKarSayisi, self.pbTamam)

        self.set_validators()

        AyarKontrolcu.ayarlari_yukle(ui=self)
        self.pbTamam.clicked.connect(lambda: AyarKontrolcu.getInstance().ayarla(ui=self))

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def set_validators(self):
        dogrulayıcı = QIntValidator(0, 250)
        self.leKitapTurBaslangic.setValidator(dogrulayıcı)
        self.leKatilimDurumuBaslangic.setValidator(dogrulayıcı)
        self.leTurBaslangic.setValidator(dogrulayıcı)
        self.leFenBaslangic.setValidator(dogrulayıcı)
        self.leOgrenciNoBaslangic.setValidator(dogrulayıcı)

        self.leMatKarSayisi.setValidator(dogrulayıcı)
        self.leFenKarSayisi.setValidator(dogrulayıcı)
        self.leTurKarSayisi.setValidator(dogrulayıcı)
        self.leKKOpakKarSayisi.setValidator(dogrulayıcı)
        self.leOgrenciNoKarSayisi.setValidator(dogrulayıcı)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Ayarlar"))
        self.groupBox_8.setTitle(_translate("Settings", "Genel Ayarlar"))
        self.groupBox_5.setTitle(_translate("Settings", "Katıldı/Katılmadı Bilgisi"))
        self.label_7.setText(_translate("Settings", "Başlangıç"))
        self.label_8.setText(_translate("Settings", "Karakter Sayısı:"))
        self.label_11.setText(_translate("Settings", "1"))
        self.groupBox_7.setTitle(_translate("Settings", "Opak/Kurum Kodu"))
        self.label_13.setText(_translate("Settings", "Başlangıç"))
        self.label_14.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_6.setTitle(_translate("Settings", "Kitapçık Türü Bilgisi"))
        self.label_9.setText(_translate("Settings", "Başlangıç"))
        self.label_10.setText(_translate("Settings", "Karakter Sayısı:"))
        self.label_12.setText(_translate("Settings", "1"))
        self.groupBox.setTitle(_translate("Settings", "Öğrenci Cevapları Opak/ K.Kodu Seçimi"))
        self.rbOpak.setText(_translate("Settings", "Opak Kullandım"))
        self.rbKKodu.setText(_translate("Settings", "K.Kodu/Ogr. No Kullandım"))
        self.groupBox_10.setTitle(_translate("Settings", "Öğrenci No"))
        self.label_15.setText(_translate("Settings", "Başlangıç"))
        self.label_16.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_9.setTitle(_translate("Settings", "Derslerle İlgili Ayarlar"))
        self.groupBox_4.setTitle(_translate("Settings", "Fen Bilimleri"))
        self.label.setText(_translate("Settings", "Başlangıç"))
        self.label_2.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_2.setTitle(_translate("Settings", "Türkçe"))
        self.label_5.setText(_translate("Settings", "Başlangıç"))
        self.label_6.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_3.setTitle(_translate("Settings", "Matematik"))
        self.label_3.setText(_translate("Settings", "Başlangıç"))
        self.label_4.setText(_translate("Settings", "Karakter Sayısı:"))
        self.pbTamam.setText(_translate("Settings", "Tamam"))

