# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog




class Ui_Settings(QDialog):


    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(416, 408)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(Settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 101))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 30, 181, 49))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbOpak = QtWidgets.QRadioButton(self.widget)
        self.rbOpak.setObjectName("rbOpak")
        self.verticalLayout.addWidget(self.rbOpak)
        self.rbKKodu = QtWidgets.QRadioButton(self.widget)
        self.rbKKodu.setObjectName("rbKKodu")
        self.verticalLayout.addWidget(self.rbKKodu)
        self.pbTamam = QtWidgets.QPushButton(Settings)
        self.pbTamam.setGeometry(QtCore.QRect(150, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbTamam.setFont(font)
        self.pbTamam.setObjectName("pbTamam")
        self.groupBox_2 = QtWidgets.QGroupBox(Settings)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 120, 181, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(87, 0))
        self.label_5.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.leTurBaslangic = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.leTurBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leTurBaslangic.setObjectName("leTurBaslangic")
        self.horizontalLayout_5.addWidget(self.leTurBaslangic)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.leTurKarSayisi = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.leTurKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leTurKarSayisi.setObjectName("leTurKarSayisi")
        self.horizontalLayout_6.addWidget(self.leTurKarSayisi)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.groupBox_3 = QtWidgets.QGroupBox(Settings)
        self.groupBox_3.setGeometry(QtCore.QRect(220, 10, 181, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(87, 0))
        self.label_3.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leMatBaslangic = QtWidgets.QLineEdit(self.layoutWidget)
        self.leMatBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leMatBaslangic.setObjectName("leMatBaslangic")
        self.horizontalLayout_3.addWidget(self.leMatBaslangic)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.leMatKarSayisi = QtWidgets.QLineEdit(self.layoutWidget)
        self.leMatKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leMatKarSayisi.setObjectName("leMatKarSayisi")
        self.horizontalLayout_4.addWidget(self.leMatKarSayisi)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox_4 = QtWidgets.QGroupBox(Settings)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 120, 201, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setMinimumSize(QtCore.QSize(87, 0))
        self.label.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.leFenBaslangic = QtWidgets.QLineEdit(self.widget1)
        self.leFenBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leFenBaslangic.setObjectName("leFenBaslangic")
        self.horizontalLayout_2.addWidget(self.leFenBaslangic)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.leFenKarSayisi = QtWidgets.QLineEdit(self.widget1)
        self.leFenKarSayisi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leFenKarSayisi.setObjectName("leFenKarSayisi")
        self.horizontalLayout.addWidget(self.leFenKarSayisi)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_5 = QtWidgets.QGroupBox(Settings)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 230, 201, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setMinimumSize(QtCore.QSize(87, 0))
        self.label_7.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.leKatilimDurumuBaslangic = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.leKatilimDurumuBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leKatilimDurumuBaslangic.setObjectName("leKatilimDurumuBaslangic")
        self.horizontalLayout_7.addWidget(self.leKatilimDurumuBaslangic)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLineWidth(2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setIndent(0)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.groupBox_6 = QtWidgets.QGroupBox(Settings)
        self.groupBox_6.setGeometry(QtCore.QRect(220, 230, 181, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 161, 57))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_9.setMinimumSize(QtCore.QSize(87, 0))
        self.label_9.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.leKitapTurBaslangic = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.leKitapTurBaslangic.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leKitapTurBaslangic.setObjectName("leKitapTurBaslangic")
        self.horizontalLayout_9.addWidget(self.leKitapTurBaslangic)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setMaximumSize(QtCore.QSize(87, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLineWidth(2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setIndent(0)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        from SettingController import AyarKontrolcu

        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Ayarlar"))
        self.groupBox.setTitle(_translate("Settings", "Öğrenci Opak/ K.Kodu Seçimi"))
        self.rbOpak.setText(_translate("Settings", "Opak Kullandım"))
        self.rbKKodu.setText(_translate("Settings", "K. Kodu/Ogr. No Kullandım"))
        self.pbTamam.setText(_translate("Settings", "Tamam"))
        self.groupBox_2.setTitle(_translate("Settings", "Türkçe"))
        self.label_5.setText(_translate("Settings", "Başlangıç"))
        self.label_6.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_3.setTitle(_translate("Settings", "Matematik"))
        self.label_3.setText(_translate("Settings", "Başlangıç"))
        self.label_4.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_4.setTitle(_translate("Settings", "Fen Bilimleri"))
        self.label.setText(_translate("Settings", "Başlangıç"))
        self.label_2.setText(_translate("Settings", "Karakter Sayısı:"))
        self.groupBox_5.setTitle(_translate("Settings", "Katıldı/Katılmadı Bilgisi"))
        self.label_7.setText(_translate("Settings", "Başlangıç"))
        self.label_8.setText(_translate("Settings", "Karakter Sayısı:"))
        self.label_11.setText(_translate("Settings", "1"))
        self.groupBox_6.setTitle(_translate("Settings", "Kitapçık Türü Bilgisi"))
        self.label_9.setText(_translate("Settings", "Başlangıç"))
        self.label_10.setText(_translate("Settings", "Karakter Sayısı:"))
        self.label_12.setText(_translate("Settings", "1"))

        self.pbTamam.clicked.connect(lambda: AyarKontrolcu.getInstance().ayarla(ui=self))










